### ISSUE TITLE
Fail to open the installed application.

### ISSUE THREAD

**Issue by UnnamedOrange** [bufhdy/Saruku#1]
<img width="420" alt="QQ20200311-190020@2x" src="https://user-images.githubusercontent.com/33177912/76410262-999d7c00-63ca-11ea-9e3a-7843285b96ca.png">

3 times has been tried.

**Comment by bufhdy** [comment]
Thanks for reporting. You might open Saruku in .dmg file, which will cause some path problem. Please open it from Applications folder. Anyway, it's an issue to be fixed 😖.

**Comment by UnnamedOrange** [comment]
I opened it both in Applications folder and  in .dmg file actually. Maybe there is a problem in digital signature.

**Comment by bufhdy** [comment]
Well, I've tired to reinstall and it went out just fine for me. It can be an option that you try some uninstaller app like [AppCleaner](https://freemacsoft.net/appcleaner/) to reinstall Saruku or build the app from source code by yourself. Or there is somewhere I made a really horrible mistake...
